In [31]:
import pandas as pd

# ================================
# CARGAR DATASET
# ================================
df = pd.read_csv("customer_shopping_data.csv")

df["invoice_date"] = pd.to_datetime(df["invoice_date"], dayfirst=True)

# ================================
# DIM_CLIENTE
# ================================
dim_cliente = df[["customer_id", "gender", "age"]].drop_duplicates()

def rango_edad(edad):
    if edad < 25:
        return "18-24"
    elif edad < 35:
        return "25-34"
    elif edad < 45:
        return "35-44"
    elif edad < 55:
        return "45-54"
    else:
        return "55+"

dim_cliente["rango_edad"] = dim_cliente["age"].apply(rango_edad)

dim_cliente = dim_cliente.rename(columns={
    "customer_id": "id_cliente",
    "gender": "genero",
    "age": "edad"
})

dim_cliente = dim_cliente.reset_index(drop=True)
dim_cliente["cliente_key"] = dim_cliente.index + 1

# ================================
# DIM_PRODUCTO
# ================================
dim_producto = df[["category"]].drop_duplicates()

dim_producto = dim_producto.rename(columns={
    "category": "categoria"
})

dim_producto = dim_producto.reset_index(drop=True)
dim_producto["producto_key"] = dim_producto.index + 1

# ================================
# DIM_METODO_PAGO
# ================================
dim_metodo_pago = df[["payment_method"]].drop_duplicates()

dim_metodo_pago = dim_metodo_pago.rename(columns={
    "payment_method": "metodo_pago"
})

dim_metodo_pago = dim_metodo_pago.reset_index(drop=True)
dim_metodo_pago["metodo_pago_key"] = dim_metodo_pago.index + 1

# ================================
# DIM_CENTRO_COMERCIAL
# ================================
dim_centro_comercial = df[["shopping_mall"]].drop_duplicates()

dim_centro_comercial = dim_centro_comercial.rename(columns={
    "shopping_mall": "nombre_centro_comercial"
})

dim_centro_comercial = dim_centro_comercial.reset_index(drop=True)
dim_centro_comercial["centro_comercial_key"] = dim_centro_comercial.index + 1

# ================================
# DIM_FECHA
# ================================
dim_fecha = pd.DataFrame()
dim_fecha["fecha_completa"] = df["invoice_date"].drop_duplicates()

dim_fecha["dia"] = dim_fecha["fecha_completa"].dt.day
dim_fecha["mes"] = dim_fecha["fecha_completa"].dt.month
dim_fecha["anio"] = dim_fecha["fecha_completa"].dt.year

dim_fecha = dim_fecha.reset_index(drop=True)
dim_fecha["fecha_key"] = dim_fecha.index + 1

# ================================
# HECHO_VENTAS
# ================================
df["monto_total"] = df["quantity"] * df["price"]

hecho_ventas = df.copy()

hecho_ventas = hecho_ventas.merge(
    dim_cliente,
    left_on=["customer_id","gender","age"],
    right_on=["id_cliente","genero","edad"]
)

hecho_ventas = hecho_ventas.merge(
    dim_producto,
    left_on="category",
    right_on="categoria"
)

hecho_ventas = hecho_ventas.merge(
    dim_metodo_pago,
    left_on="payment_method",
    right_on="metodo_pago"
)

hecho_ventas = hecho_ventas.merge(
    dim_centro_comercial,
    left_on="shopping_mall",
    right_on="nombre_centro_comercial"
)

hecho_ventas = hecho_ventas.merge(
    dim_fecha,
    left_on="invoice_date",
    right_on="fecha_completa"
)

hecho_ventas = hecho_ventas.rename(columns={
    "invoice_no": "numero_factura",
    "quantity": "cantidad"
})

hecho_ventas = hecho_ventas[[
    "numero_factura",
    "cliente_key",
    "producto_key",
    "fecha_key",
    "centro_comercial_key",
    "metodo_pago_key",
    "cantidad",
    "monto_total"
]]

hecho_ventas = hecho_ventas.reset_index(drop=True)
hecho_ventas["id_venta"] = hecho_ventas.index + 1

print("ETL completado")

ETL completado

In [32]:
dim_cliente.head()

  id_cliente  genero  edad rango_edad  cliente_key
0    C241288  Female    28      25-34            1
1    C111565    Male    21      18-24            2
2    C266599    Male    20      18-24            3
3    C988172  Female    66        55+            4
4    C189076  Female    53      45-54            5

In [33]:
dim_producto.head()

         categoria  producto_key
0         Clothing             1
1            Shoes             2
2            Books             3
3        Cosmetics             4
4  Food & Beverage             5

In [34]:
dim_metodo_pago.head()

   metodo_pago  metodo_pago_key
0  Credit Card                1
1   Debit Card                2
2         Cash                3

In [35]:
dim_centro_comercial.head()

  nombre_centro_comercial  centro_comercial_key
0                  Kanyon                     1
1          Forum Istanbul                     2
2               Metrocity                     3
3            Metropol AVM                     4
4            Istinye Park                     5

In [36]:
hecho_ventas.head()

,numero_factura,cliente_key,producto_key,fecha_key,centro_comercial_key,metodo_pago_key,cantidad,monto_total,id_venta
0,I138884,1,1,1,1,1,5,7502.00,1
1,I236201,1952,1,1,1,1,2,1200.32,2
2,I305612,52003,1,1,1,1,3,2700.72,3
3,I239410,56534,1,1,1,1,3,2700.72,4
4,I238493,70397,1,1,1,1,1,300.08,5

In [37]:
from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:1234@localhost:5432/bodega_ventas")

In [38]:
print(dim_cliente.columns)

Index(['id_cliente', 'genero', 'edad', 'rango_edad', 'cliente_key'], dtype='object')

In [39]:
dim_cliente.to_sql(
    "dim_cliente",
    engine,
    if_exists="append",
    index=False
)

dim_producto.to_sql(
    "dim_producto",
    engine,
    if_exists="append",
    index=False
)

dim_fecha.to_sql(
    "dim_fecha",
    engine,
    if_exists="append",
    index=False
)

dim_metodo_pago.to_sql(
    "dim_metodo_pago",
    engine,
    if_exists="append",
    index=False
)

dim_centro_comercial.to_sql(
    "dim_centro_comercial",
    engine,
    if_exists="append",
    index=False
)

IntegrityError: (psycopg2.errors.UniqueViolation) llave duplicada viola restricción de unicidad «dim_cliente_pkey»
DETAIL:  Ya existe la llave (cliente_key)=(1).

[SQL: INSERT INTO dim_cliente (id_cliente, genero, edad, rango_edad, cliente_key) VALUES (%(id_cliente)s, %(genero)s, %(edad)s, %(rango_edad)s, %(cliente_key)s)]
[parameters: ({'id_cliente': 'C241288', 'genero': 'Female', 'edad': 28, 'rango_edad': '25-34', 'cliente_key': 1}, {'id_cliente': 'C111565', 'genero': 'Male', 'edad': 21, 'rango_edad': '18-24', 'cliente_key': 2}, {'id_cliente': 'C266599', 'genero': 'Male', 'edad': 20, 'rango_edad': '18-24', 'cliente_key': 3}, {'id_cliente': 'C988172', 'genero': 'Female', 'edad': 66, 'rango_edad': '55+', 'cliente_key': 4}, {'id_cliente': 'C189076', 'genero': 'Female', 'edad': 53, 'rango_edad': '45-54', 'cliente_key': 5}, {'id_cliente': 'C657758', 'genero': 'Female', 'edad': 28, 'rango_edad': '25-34', 'cliente_key': 6}, {'id_cliente': 'C151197', 'genero': 'Female', 'edad': 49, 'rango_edad': '45-54', 'cliente_key': 7}, {'id_cliente': 'C176086', 'genero': 'Female', 'edad': 32, 'rango_edad': '25-34', 'cliente_key': 8}  ... displaying 10 of 99457 total bound parameter sets ...  {'id_cliente': 'C800631', 'genero': 'Male', 'edad': 56, 'rango_edad': '55+', 'cliente_key': 99456}, {'id_cliente': 'C273973', 'genero': 'Female', 'edad': 36, 'rango_edad': '35-44', 'cliente_key': 99457})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)

In [ ]:
hecho_ventas.to_sql(
    "hecho_ventas",
    engine,
    if_exists="append",
    index=False
)

457